const e=JSON.parse('{"key":"v-583cf311","path":"/code/python/python-exception.html","title":"8.1 异常处理","lang":"zh-CN","frontmatter":{"category":"Python","description":"8.1 异常处理 错误 Error 逻辑错误：算法写错了，例如加法写成了减法 笔误：例如变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去。 例如open函数操作一个文件，文件不存在，或者创建一个文件时已经存在了，或者访问一个网络文件，突然断网了，这就是异常，是个意外的情况。","head":[["meta",{"property":"og:url","content":"https://clay-wangzhi.com/code/python/python-exception.html"}],["meta",{"property":"og:site_name","content":"SRE运维进阶之路"}],["meta",{"property":"og:title","content":"8.1 异常处理"}],["meta",{"property":"og:description","content":"8.1 异常处理 错误 Error 逻辑错误：算法写错了，例如加法写成了减法 笔误：例如变量名写错了，语法错误 函数或类使用错误，其实这也属于逻辑错误 总之，错误是可以避免的 异常 Exception 本意就是意外情况 这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去。 例如open函数操作一个文件，文件不存在，或者创建一个文件时已经存在了，或者访问一个网络文件，突然断网了，这就是异常，是个意外的情况。"}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2023-04-19T13:08:31.000Z"}],["meta",{"property":"article:author","content":"Clay"}],["meta",{"property":"article:modified_time","content":"2023-04-19T13:08:31.000Z"}],["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"8.1 异常处理\\",\\"image\\":[\\"\\"],\\"dateModified\\":\\"2023-04-19T13:08:31.000Z\\",\\"author\\":[{\\"@type\\":\\"Person\\",\\"name\\":\\"Clay\\",\\"url\\":\\"https://clay-wangzhi.com\\"}]}"]]},"headers":[{"level":2,"title":"产生异常","slug":"产生异常","link":"#产生异常","children":[]},{"level":2,"title":"异常的捕获","slug":"异常的捕获","link":"#异常的捕获","children":[]},{"level":2,"title":"异常类及继承层次","slug":"异常类及继承层次","link":"#异常类及继承层次","children":[]},{"level":2,"title":"BaseException 及子类","slug":"baseexception-及子类","link":"#baseexception-及子类","children":[{"level":3,"title":"BaseException","slug":"baseexception","link":"#baseexception","children":[]},{"level":3,"title":"SystemExit","slug":"systemexit","link":"#systemexit","children":[]},{"level":3,"title":"KeyboardInterrupt","slug":"keyboardinterrupt","link":"#keyboardinterrupt","children":[]}]},{"level":2,"title":"Exception及子类","slug":"exception及子类","link":"#exception及子类","children":[]},{"level":2,"title":"多种捕获","slug":"多种捕获","link":"#多种捕获","children":[]},{"level":2,"title":"as 子句","slug":"as-子句","link":"#as-子句","children":[]},{"level":2,"title":"finally子句","slug":"finally子句","link":"#finally子句","children":[]},{"level":2,"title":"else 子句","slug":"else-子句","link":"#else-子句","children":[]},{"level":2,"title":"总结","slug":"总结","link":"#总结","children":[]}],"git":{"createdTime":1681909711000,"updatedTime":1681909711000,"contributors":[{"name":"clay-wangzhi","email":"clay.wangzhi@gmail.com","commits":1}]},"readingTime":{"minutes":6.66,"words":1998},"filePathRelative":"code/python/python-exception.md","localizedDate":"2023年4月19日","excerpt":"<h1> 8.1 异常处理</h1>\\n<p><strong>错误 Error</strong></p>\\n<p>逻辑错误：算法写错了，例如加法写成了减法</p>\\n<p>笔误：例如变量名写错了，语法错误</p>\\n<p>函数或类使用错误，其实这也属于逻辑错误</p>\\n<p>总之，错误是可以避免的</p>\\n<p><strong>异常 Exception</strong></p>\\n<p>本意就是意外情况</p>\\n<p>这有个前提，没有出现上面说的错误，也就是说程序写的没有问题，但是在某些情况下，会出现一些意外，导致程序无法正常的执行下去。</p>\\n<p>例如open函数操作一个文件，文件不存在，或者创建一个文件时已经存在了，或者访问一个网络文件，突然断网了，这就是异常，是个意外的情况。</p>","copyright":{"author":"Clay"},"autoDesc":true}');export{e as data};
